apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api-deployment
spec:
  selector:
    matchLabels:
      app: test-api-pod
  template:
    metadata:
      labels:
        app: test-api-pod
    spec:
      containers:
        - name: api
          image: api:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
