apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-test-mysql-pv-claim
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  local:
    path: "D:\\DockerSharedVolume"
